# Renew cert
- id: enable_renew_cert
  alias: Enable Renew certificate
  hide_entity: true
  trigger:
  - platform: state
    entity_id: input_boolean.renew_certificate
    to: 'on'
  - platform: numeric_state
    entity_id: sensor.ssl_certificate_expiry 
    below: 7
  action:
  - service: hassio.addon_start
    data:
      addon: "core_letsencrypt"
  - delay: "00:00:05"
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.renew_certificate

# Themperature
- id: temp_to_sleep
  alias: Tempetatuur op slaap modus
  trigger:
  - platform: time
    at: "23:00:00"
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.toon_thermostat
        temperature: 18
- id: temp_to_wakeup
  alias: Tempetatuur op opstaan
  trigger:
  - platform: time
    at: "06:00:00"
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.toon_thermostat
        temperature: 21
    
# Toilet lamp aan
- id: toilet_light_on
  alias: Toilet lamp aan
  hide_entity: true
  trigger:
  - platform: state
    entity_id: binary_sensor.0x00158d00040c7074_occupancy
    to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.0x086bd7fffe0505af_light
        transition: 20
        brightness: 100
- id: toilet_lights_off_5min
  alias: Toilet lamp uit 
  trigger:
    platform: state
    entity_id: binary_sensor.0x00158d00040c7074_occupancy
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    data:
      entity_id: light.0x086bd7fffe0505af_light
      transition: 20

# Zigbee
- id: enable_zigbee_join
  alias: Enable Zigbee joining
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_boolean.zigbee_permit_join
    to: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'true'
  - service: timer.start
    data:
      entity_id: timer.zigbee_permit_join
- id: disable_zigbee_join
  alias: Disable Zigbee joining
  trigger:
  - entity_id: input_boolean.zigbee_permit_join
    platform: state
    to: 'off'
  action:
  - data:
      payload: 'false'
      topic: zigbee2mqtt/bridge/config/permit_join
    service: mqtt.publish
  - data:
      entity_id: timer.zigbee_permit_join
    service: timer.cancel
  hide_entity: true
- id: disable_zigbee_join_timer
  alias: Disable Zigbee joining by timer
  hide_entity: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee_permit_join
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'false'
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.zigbee_permit_join
- id: update_networkmap
  alias: 'Zigbee Map aktualisieren'  
  hide_entity: true  
  trigger:
    platform: time_pattern
    minutes: '/10'
    seconds: 00
  action:
    service: zigbee2mqtt_networkmap.update
