
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml

binary_sensor: !include_dir_merge_list binary_sensors
device_tracker: !include_dir_merge_named device_trackers 
input_boolean: !include_dir_merge_named input_boolean
light: !include_dir_merge_named lights
sensor: !include_dir_merge_list sensors
timer: !include_dir_merge_list timers
zone: !include_dir_merge_list zones

# Google calendar
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: false

# Panels 
panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    url: '/local/community/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'

# Toon
toon:
  client_id: !secret toon_consumer_key
  client_secret: !secret toon_consumer_secret

# Yeelight
yeelight:
  devices:
    10.61.2.128:
      name: Lamp Woonkamer TV-kast 
    10.61.2.129:
      name: Lamp Woonkamer Wit-tafeltje 

# Zigbee2mqtt
zigbee2mqtt_networkmap:
