- platform: broadlink
  host: !secret broadlink_woonkamer_ip
  mac: !secret broadlink_woonkamer_mac
  name: Broadlink_woonkamer
- platform: broadlink
  host: !secret broadlink_slaapkamer_ip
  mac: !secret broadlink_slaapkamer_mac
  name: Broadlink_slaapkamer
