- platform: xiaomi_miio
  name: Lamp Woonkamer plafon 001
  host: 10.61.2.130
  token: !secret xiaomi_001
- platform: xiaomi_miio
  name: Lamp Woonkamer plafon 002
  host: 10.61.2.131
  token: !secret xiaomi_002
- platform: xiaomi_miio
  name: Lamp Woonkamer plafon 003
  host: 10.61.2.132
  token: !secret xiaomi_003
- platform: xiaomi_miio
  name: Lamp Eetkamer plafon 001
  host: 10.61.2.133
  token: !secret xiaomi_004
- platform: xiaomi_miio
  name: Lamp Eetkamer plafon 002
  host: 10.61.2.134
  token: !secret xiaomi_005
- platform: xiaomi_miio
  name: Lamp Eetkamer plafon 003
  host: 10.61.2.135
  token: !secret xiaomi_006
