- platform: mqtt
  name: 'Muur lamp'
  state_topic: 'tasmota/outside/wall1/stat/POWER'
  command_topic: 'tasmota/outside/wall1/cmnd/POWER'
  availability_topic: 'tasmota/outside/wall1/tele/LWT'
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  payload_available: Online
  payload_not_available: Offline
  retain: false

- platform: mqtt
  name: 'Buitenlamp muur'
  state_topic: 'tasmota/outside/wall1/stat/POWER'
  command_topic: 'tasmota/outside/wall1/cmnd/POWER'
  availability_topic: 'tasmota/outside/wall1/tele/LWT'
  brightness_state_topic: 'tasmota/outside/wall1/stat/Dimmer'
  brightness_command_topic: 'tasmota/outside/wall1/cmnd/Dimmer'
  brightness_scale: 100
  color_temp_state_topic: 'tasmota/outside/wall1/stat/CT'
  color_temp_command_topic: 'tasmota/outside/wall1/cmnd/CT' 
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  payload_available: Online
  payload_not_available: Offline
  retain: false
