- platform: mqtt
  name: 'Muur lamp'
  state_topic: 'tasmota/outside/wall1/stat/POWER'
  command_topic: 'tasmota/outside/wall1/cmnd/POWER'
  availability_topic: 'tasmota/outside/wall1/tele/STATE'
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  payload_available: Online
  payload_not_available: Offline
  retain: false
