######################################################################
##  Certificate for https expires in
######################################################################

- platform: cert_expiry
  host: home-assistant.io
