######################################################################
##  Fritzbox net monitor
######################################################################

- platform: fritzbox_netmonitor
  host: 10.61.0.1
  name: Fritz
