######################################################################
##  Morning routine workday Minou
######################################################################
#   Runs 2 hours before her workday
#   Input is calendar based


- alias: Werkdag ochtend ritueel Minou
  trigger:
    platform: template
    value_template: "{{ ((as_timestamp(states.calendar.minou_werk.attributes.start_time) - as_timestamp(states.sensor.time.last_changed)) < 7200) }}"

  condition:
    condition: or  # 'when dark' condition: either after sunset or before sunrise - equivalent to a state condition on `sun.sun` of `below_horizon`
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-02:00:00"
      - condition: sun
        before: sunrise
        before_offset: "02:00:00"

  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.morning_routine_minou
    - service: climate.set_temperature
      data:
        entity_id: climate.toon_thermostat
        temperature: 20
    - delay: "00:45:00" # The alarm clock rings
    - service: light.turn_on
      data:
        entity_id: light.0x14b457fffe44351d_light
        brightness: 1
    - service: light.turn_on
      data:
        entity_id: light.0x14b457fffe44351d_light
        transition: 180 # 3 mins to bright light
        brightness: 200
    - delay: "00:5:00" # make-up time
    - service: light.turn_on
      data:
        entity_id:
          - group.lamp_woonkamer_plafon
          - group.lamp_eetkamer_plafon
        transition: 120
        brightness: 150
    - service: light.turn_on
      data:
        entity_id: light.0x14b457fffe44351d_light
        brightness: 50
    - delay: '01:10:00'
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.morning_routine_minou
