######################################################################
##  Morning routine workday Dennis
######################################################################
#   Runs 2 hours before my workday
#   Input is calendar based

- alias: Werkdag ochtend ritueel Dennis
  trigger:
    platform: template
    value_template: "{{ ((as_timestamp(states.calendar.dennis_werk.attributes.start_time) - as_timestamp(states.sensor.time.last_changed)) < 7200) }}"

  condition:
    condition: or  # 'when dark' condition: either after sunset or before sunrise - equivalent to a state condition on `sun.sun` of `below_horizon`
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-02:00:00"
      - condition: sun
        before: sunrise
        before_offset: "02:00:00"

  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.morning_routine_dennis
    - service: climate.set_temperature
      data:
        entity_id: climate.toon_thermostat
        temperature: 20
    - delay: "00:40:00" # The alarm clock rings
    - service: light.turn_on
      data:
        entity_id: light.0x14b457fffe44351d_light
        brightness: 1
    - service: light.turn_on
      data:
        entity_id: light.0x14b457fffe44351d_light
        transition: 180 # 3 mins to bright light
        brightness: 200
    - delay: '00:05:00' # D. is probebly getting down stairs
    - service: light.turn_on
      data:
        entity_id: light.0x14b457fffe44351d_light
        brightness: 100
    - delay: '01:15:00' # Delay the remaining time (trigger is set for 2 hours before)
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.morning_routine_dennis
