######################################################################
##  Morning routine workday Dennis
######################################################################
#   Runs 2 hours before my workday
#   Input is calendar based

- alias: Werkdag ochtend ritueel Dennis
  trigger:
    platform: template
    value_template: "{{ ((as_timestamp(states.calendar.dennis_werk.attributes.start_time) - as_timestamp(states.sensor.time.last_changed)) < 7200) }}"

  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.morning_routine_dennis
    - service: climate.set_temperature
      data:
        entity_id: climate.toon_thermostat
        temperature: 20    
    - delay: "00:40:00" # The alarm clock rings
    - service: light.turn_on
      data:
        entity_id: light.0x14b457fffe44351d_light
        transition: 180 # 3 mins to bright light
        brightness: 100

## Hall light on motion
- alias: Hal lamp aan Dennis

  trigger:
    platform: state
    entity_id: binary_sensor.0x00158d00042427fd_occupancy
    to: 'on'
    
  condition:
    - condition: state
      entity_id: input_boolean.morning_routine_dennis
      state: 'on'

  action:
    - service: light.turn_on
      data:
        entity_id: light.0x14b457fffe44351d_light
        transition: 180 # 3 mins to bright light
        brightness: 225

## Input boolean turn back off
- alias: Dennis zijn ochtendroutine uit
  
  trigger:
    platform: state
    entity_id: input_boolean.morning_routine_dennis
    to: 'on'
    for:
      hours: 3
    
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.morning_routine_dennis
