######################################################################
##  Motion by frontdoor turn lights on and off
######################################################################
#   Input is motion dectection

#########################
## Frontdoor lights on ##
#########################
- alias: Hal lamp aan
  hide_entity: true

  trigger:
    platform: state
    entity_id: binary_sensor.0x00158d0004508239_occupancy
    to: 'on'

  condition:
    - condition: or
      conditions:
      - condition: sun
        after: sunset
        after_offset: "-02:00:00"
      - condition: sun
        before: sunrise
        before_offset: "02:00:00"

  action:
    - service: light.turn_on
      data:
        entity_id: light.0x14b457fffe52867d_light
        transition: 30
        brightness: 100

##########################
## Frontdoor lights off ##
##########################
- alias: Hal lamp uit
  hide_entity: true

  trigger:
    platform: state
    entity_id: binary_sensor.0x00158d0004508239_occupancy
    to: 'off'
    for:
      minutes: 5
  
  action:
    service: light.turn_off
    data:
      entity_id: light.0x14b457fffe52867d_light
      transition: 60
